import type { Config } from '@puckeditor/core';
import { DesignCollection, DesignContact, DesignFAQ, DesignFooter, DesignHeader, DesignHero, DesignStory } from './DesignBlocks';
import type { DesignBlockProps } from './types';

const text = (label: string) => ({ type: 'text' as const, label });
const longText = (label: string) => ({ type: 'textarea' as const, label });
const links = { type: 'array' as const, label: 'Пункты меню', arrayFields: { label: text('Название'), href: text('Якорь (#contact)') }, defaultItemProps: { label: 'Контакт', href: '#contact' } };
const yesNo = (label: string) => ({ type: 'radio' as const, label, options: [{ label: 'Да', value: true }, { label: 'Нет', value: false }] });

export const designComponents: Config<DesignBlockProps>['components'] = {
  DesignHeader: { label: 'Дизайн: навигация', fields: { brand: text('Название'), descriptor: text('Подпись'), links, action: text('Кнопка') }, defaultProps: { brand: 'ДЕМО', descriptor: 'Демонстрационный дизайн', links: [], action: 'Демо-заявка' }, render: (props) => <DesignHeader {...props} /> },
  DesignHero: { label: 'Дизайн: первый экран', fields: { eyebrow: text('Надзаголовок'), title: longText('Заголовок'), text: longText('Описание'), image: text('Публичное изображение'), imageAlt: text('Описание изображения'), caption: text('Подпись к фото'), action: text('Кнопка'), href: text('Якорь кнопки'), secondary: text('Вторая ссылка'), secondaryHref: text('Второй якорь') }, defaultProps: { eyebrow: 'Демонстрационный дизайн', title: 'Название проекта', text: 'Описание', image: '', imageAlt: '', caption: 'Иллюстративная фотография', action: 'Подробнее', href: '#contact', secondary: 'О проекте', secondaryHref: '#about' }, render: (props) => <DesignHero {...props} /> },
  DesignCollection: { label: 'Дизайн: коллекция', fields: { idAnchor: text('Якорь секции'), eyebrow: text('Надзаголовок'), title: text('Заголовок'), text: longText('Введение'), layout: { type: 'select', label: 'Подача', options: [{ label: 'Карточки', value: 'cards' }, { label: 'Список', value: 'list' }, { label: 'Меню', value: 'menu' }, { label: 'Товары', value: 'products' }, { label: 'Расписание', value: 'schedule' }, { label: 'Этапы', value: 'steps' }, { label: 'Сравнение', value: 'comparison' }, { label: 'Галерея', value: 'gallery' }] }, filter: yesNo('Фильтр по категориям'), items: { type: 'array', label: 'Элементы', arrayFields: { title: text('Название'), text: longText('Описание'), tag: text('Категория'), image: text('Публичное изображение'), imageAlt: text('Описание фото'), detail: longText('Подробности'), meta: text('Подпись') }, defaultItemProps: { title: 'Новый элемент', text: 'Описание' } }, action: text('Демо-действие (пусто — без кнопки)') }, defaultProps: { idAnchor: 'collection', eyebrow: 'Демонстрация', title: 'Коллекция', text: '', layout: 'cards', filter: false, items: [], action: '' }, render: (props) => <DesignCollection {...props} /> },
  DesignStory: { label: 'Дизайн: фото и история', fields: { idAnchor: text('Якорь'), eyebrow: text('Надзаголовок'), title: text('Заголовок'), text: longText('Описание'), image: text('Фото'), imageAlt: text('Описание фото'), caption: text('Подпись'), reverse: yesNo('Фото справа'), points: { type: 'array', label: 'Пункты', arrayFields: { text: text('Текст') }, defaultItemProps: { text: 'Пункт' } } }, defaultProps: { idAnchor: 'about', eyebrow: 'О проекте', title: 'Наша история', text: '', image: '', imageAlt: '', caption: 'Иллюстративная фотография', reverse: false, points: [] }, render: (props) => <DesignStory {...props} /> },
  DesignFAQ: { label: 'Дизайн: вопросы', fields: { idAnchor: text('Якорь'), title: text('Заголовок'), items: { type: 'array', label: 'Вопросы', arrayFields: { question: text('Вопрос'), answer: longText('Ответ') }, defaultItemProps: { question: 'Это демонстрация?', answer: 'Да, без внешней отправки данных.' } } }, defaultProps: { idAnchor: 'faq', title: 'Вопросы и ответы', items: [] }, render: (props) => <DesignFAQ {...props} /> },
  DesignContact: { label: 'Дизайн: учебная форма', fields: { idAnchor: text('Якорь'), eyebrow: text('Надзаголовок'), title: text('Заголовок'), text: longText('Описание'), options: { type: 'array', label: 'Варианты обращения', arrayFields: { label: text('Название') }, defaultItemProps: { label: 'Демонстрация' } }, action: text('Кнопка'), addressNote: longText('Адрес: только реальный или явно не указан') }, defaultProps: { idAnchor: 'contact', eyebrow: 'Без внешних отправок', title: 'Попробуйте демо-форму', text: 'Не указывайте личные данные.', options: [{ label: 'Общий вопрос' }], action: 'Проверить форму', addressNote: '' }, render: (props) => <DesignContact {...props} /> },
  DesignFooter: { label: 'Дизайн: подвал', fields: { brand: text('Название'), text: longText('Описание'), links }, defaultProps: { brand: 'ДЕМО', text: 'Демонстрационный дизайн.', links: [] }, render: (props) => <DesignFooter {...props} /> },
};
