import { Download, LockKeyhole, Mail, Network, Play, Save, Send, Upload } from 'lucide-react';
import { useMemo, useRef, useState } from 'react';
import { unlockLabAchievement } from '../core/storage';
import { authenticateLabServer, chatReply, connectRetroNetwork, createRetroBackup, installRetroApp, openRetroMail, parseBasic, parseRetroBackup, retroComputers, retroMail, runBasic, sanitizeRetroCss, sanitizeRetroHtml, saveBasicProgram, saveMailAttachment, type RetroBackup } from './retroAdventure';
import { type RetroState } from './retroState';

type Props = { state: RetroState; onChange: (state: RetroState) => void };

export function RetroNetwork({ state, onChange }: Props) {
  const [selected, setSelected] = useState<string>(); const [user, setUser] = useState(''); const [password, setPassword] = useState(''); const [error, setError] = useState('');
  const connect = () => { onChange(connectRetroNetwork(state)); unlockLabAchievement('RETRO_NETWORKED'); };
  const login = () => { const result = authenticateLabServer(state, user, password); if (!result.ok) { setError('Неверное игровое имя или пароль. Ищите подсказки в файлах, почте и #core.'); return; } onChange(result.state); setError(''); unlockLabAchievement('RETRO_SYSADMIN'); };
  return <div className="retro-network"><header><Network /><strong>СЕТЕВОЕ ОКРУЖЕНИЕ</strong><button type="button" onClick={connect}>{state.network.connected ? 'ПОДКЛЮЧЕНО' : 'ПОДКЛЮЧИТЬСЯ'}</button></header>{!state.network.connected ? <p>Это игровая виртуальная сеть SITEVL. Она не сканирует устройства пользователя.</p> : <div>{retroComputers.map((computer) => <button type="button" onClick={() => setSelected(computer.id)} key={computer.id}><i className={computer.id === 'server' ? 'is-locked' : ''} /><span><strong>{computer.name}</strong><small>{computer.id === 'server' && state.network.labServerUnlocked ? '● ДОСТУП РАЗРЕШЁН' : `● ${computer.status}`}</small></span></button>)}</div>}{selected === 'server' && !state.network.labServerUnlocked ? <form onSubmit={(event) => { event.preventDefault(); login(); }}><LockKeyhole /><strong>ТРЕБУЕТСЯ АВТОРИЗАЦИЯ</strong><input value={user} onChange={(event) => setUser(event.target.value)} placeholder="Имя пользователя" autoComplete="off" /><input type="password" value={password} onChange={(event) => setPassword(event.target.value)} placeholder="Игровой пароль" autoComplete="off" /><button type="submit">ВОЙТИ</button>{error ? <p>{error}</p> : null}</form> : selected ? <section><strong>{retroComputers.find((item) => item.id === selected)?.name}</strong><p>{selected === 'server' ? 'LAB SERVER STORAGE: ARCHIVE · LOGS · PROJECTS · CORE · UNKNOWN' : '\\Shared доступна через общий виртуальный диск.'}</p></section> : null}</div>;
}

export function RetroMail({ state, onChange }: Props) { const [selected, setSelected] = useState(retroMail[0].id); const message = retroMail.find((item) => item.id === selected) || retroMail[0]; const open = (id: string) => { setSelected(id); onChange(openRetroMail(state, id)); unlockLabAchievement('RETRO_MAIL_USER'); }; return <div className="retro-mail"><aside><strong>ПОЧТА</strong><button type="button">Входящие ({retroMail.length})</button><button type="button">Отправленные</button><button type="button">Черновики</button><button type="button">Корзина</button></aside><section><nav>{retroMail.map((item) => <button className={item.id === selected ? 'is-active' : ''} type="button" onClick={() => open(item.id)} key={item.id}><Mail /><span><strong>{item.subject}</strong><small>{item.from}</small></span></button>)}</nav><article><small>ОТ: {message.from}</small><h3>{message.subject}</h3><p>{message.body}</p>{message.attachment ? <button type="button" disabled={state.mail.savedAttachmentIds.includes(message.id)} onClick={() => onChange(saveMailAttachment(state, message.id))}><Save /> {state.mail.savedAttachmentIds.includes(message.id) ? 'СОХРАНЕНО' : `СОХРАНИТЬ ${message.attachment.name}`}</button> : null}</article></section></div>; }

export function RetroChat({ state, onChange }: Props) { const [channel, setChannel] = useState('general'); const [value, setValue] = useState(''); const [messages, setMessages] = useState<Record<string, string[]>>({ general: ['SYSOP: Локальная сеть активна.'], retro: ['MONO: Три оболочки, один диск.'], lab: ['ADMIN: CORE остаётся закрыт.'], help: ['SYSOP: Введите /help.'], core: ['NULL: ...'] }); const send = () => { if (!value.trim()) return; const result = chatReply(state, channel, value); onChange(result.state); if (result.state.chat.discoveredCore) unlockLabAchievement('RETRO_SYSOP'); setMessages((current) => ({ ...current, [channel]: [...(current[channel] || []), `GUEST42: ${value}`, result.reply] })); if (value.startsWith('/join #')) setChannel(value.slice(7)); if (value === '/clear') setMessages((current) => ({ ...current, [channel]: [] })); setValue(''); }; const channels = ['general', 'retro', 'lab', 'help', ...(state.chat.discoveredCore ? ['core'] : [])]; return <div className="retro-chat"><aside>{channels.map((item) => <button className={channel === item ? 'is-active' : ''} type="button" onClick={() => setChannel(item)} key={item}>#{item}</button>)}</aside><section><header>LAB IRC / #{channel}</header><div>{(messages[channel] || []).map((item, index) => <p key={`${item}-${index}`}>{item}</p>)}</div><form onSubmit={(event) => { event.preventDefault(); send(); }}><input value={value} onChange={(event) => setValue(event.target.value)} placeholder="Сообщение или /help" /><button type="submit" aria-label="Отправить"><Send /></button></form></section></div>; }

export function RetroBasic({ state, onChange }: Props) { const [source, setSource] = useState('PRINT "ПРИВЕТ SITEVL"\nCOLOR BLUE\nBEEP\nWAIT 300\nLET X 5\nADD X 7\nPRINT "SYSTEM READY" X'); const [output, setOutput] = useState<string[]>([]); const run = async () => { const parsed = parseBasic(source); if (!parsed.ok) { setOutput([parsed.error]); return; } setOutput([]); await runBasic(parsed.program, (value) => setOutput((items) => value === '\u0000' ? [] : [...items, value])); onChange(saveBasicProgram(state, source)); unlockLabAchievement('RETRO_PROGRAMMER'); }; return <div className="retro-basic"><header><strong>SITEVL BASIC</strong><button type="button" onClick={() => void run()}><Play /> ЗАПУСТИТЬ</button></header><div><textarea value={source} onChange={(event) => setSource(event.target.value)} spellCheck={false} aria-label="Программа SITEVL BASIC" /><output>{output.map((item, index) => <span key={`${item}-${index}`}>{item}</span>)}</output></div></div>; }

export function RetroWebLab({ state, onChange }: Props) { const [html, setHtml] = useState('<main>\n  <h1>Мой сайт 1998</h1>\n  <p>Добро пожаловать в сеть.</p>\n  <button>Написать</button>\n</main>'); const [css, setCss] = useState('body { background: navy; color: white; font-family: monospace; text-align: center; padding: 40px; }\nbutton { padding: 10px; }'); const safe = useMemo(() => `<!doctype html><style>${sanitizeRetroCss(css)}</style>${sanitizeRetroHtml(html)}`, [css, html]); const save = () => { onChange({ ...state, files: [...state.files.filter((item) => item.id !== 'my-site'), { id: 'my-site', parentId: 'development', name: 'MY_SITE.SVW', kind: 'text', content: JSON.stringify({ html, css }), createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() }] }); unlockLabAchievement('RETRO_WEBMASTER'); }; return <div className="retro-weblab"><header><strong>HTML LAB · JAVASCRIPT ОТКЛЮЧЁН</strong><button type="button" onClick={save}><Save /> СОХРАНИТЬ ПРОЕКТ</button></header><div><label>HTML<textarea value={html} onChange={(event) => setHtml(event.target.value)} /></label><label>CSS<textarea value={css} onChange={(event) => setCss(event.target.value)} /></label><iframe title="Безопасный результат HTML LAB" sandbox="" srcDoc={safe} /></div></div>; }

export function RetroSoftware({ state, onChange }: Props) { const packages = [{ id: 'paintplus', label: 'PAINTPLUS.SVP' }, { id: 'gamepack', label: 'GAMEPACK.SVP' }, { id: 'player', label: 'PLAYER.SVP' }]; return <div className="retro-software"><h3>SOFTWARE ARCHIVE</h3><p>Виртуальные пакеты SVP не выполняют системный код.</p>{packages.map((item) => <article key={item.id}><strong>{item.label}</strong><button type="button" disabled={state.installedApps.includes(item.id)} onClick={() => { onChange(installRetroApp(state, item.id)); unlockLabAchievement('RETRO_INSTALLER'); }}>{state.installedApps.includes(item.id) ? 'УСТАНОВЛЕНО' : 'УСТАНОВИТЬ'}</button></article>)}</div>; }

export function RetroBackupApp({ state, onChange }: Props) { const inputRef = useRef<HTMLInputElement>(null); const exportBackup = () => { const backup = createRetroBackup(state); const url = URL.createObjectURL(new Blob([JSON.stringify(backup, null, 2)], { type: 'application/json' })); const anchor = document.createElement('a'); anchor.href = url; anchor.download = 'sitevl-retro-backup.json'; anchor.click(); URL.revokeObjectURL(url); }; const importBackup = async (file?: File) => { if (!file) return; try { const parsed = parseRetroBackup(JSON.parse(await file.text()) as RetroBackup); if (!parsed.ok) return window.alert(parsed.error); if (window.confirm(`Импортировать backup: ${parsed.state.files.length} файлов, ${parsed.state.installedApps.length} приложений?`)) onChange(parsed.state); } catch { window.alert('Файл backup повреждён.'); } }; return <div className="retro-backup"><h3>BACKUP RETRO COMPUTER</h3><p>Экспорт включает виртуальные файлы, настройки, приложения, закладки, квест и результаты. Камера и микрофон не экспортируются.</p><button type="button" onClick={exportBackup}><Download /> ЭКСПОРТИРОВАТЬ JSON</button><button type="button" onClick={() => inputRef.current?.click()}><Upload /> ИМПОРТИРОВАТЬ</button><input ref={inputRef} hidden type="file" accept="application/json,.json" onChange={(event) => void importBackup(event.target.files?.[0])} /></div>; }
