import { writeFile } from 'node:fs/promises';
import { publishedTemplates, getTemplatePackage } from '../src/features/site-builder/catalog/catalog';
import { loadTemplateProject } from '../src/features/site-builder/catalog/projectLoaders';
import { enableCustomizer } from '../src/features/site-builder/customizer/model';
import { applyFont, fontPairs } from '../src/features/site-builder/customizer/theme';

// Generated server contract, not a second authored source of prices or designs.
const entries = await Promise.all(publishedTemplates.map(async meta => {
  const loaded = await loadTemplateProject(meta);
  const project = enableCustomizer(loaded.project, meta.version);
  return { id: meta.id, version: meta.version, slug: meta.slug, name: meta.name,
    package: getTemplatePackage(meta), project,
    typography: fontPairs.map(pair => applyFont(project.theme, pair.id).typography) };
}));
await writeFile(new URL('../api/_templateContract.generated.mjs', import.meta.url),
  '// Generated by scripts/generate-template-contract.ts. Do not edit prices here.\nexport const templateContract = ' + JSON.stringify(entries, null, 2) + ';\n');
console.log(`Template server contract: ${entries.length} designs, shared pricing.`);
