import { Crosshair, Expand, Flag, Gamepad2, Gauge, Heart, Pause, Play, RotateCw, Shield, Trophy, Zap } from 'lucide-react';
import { useCallback, useEffect, useRef, useState } from 'react';
import type { ModernGameId, ModernOsState } from './modernOsModel';
import { ModernTouchButton } from './ModernTouchButton';

type GameProps = { haptics: boolean; onExit: () => void; onResult: (id: ModernGameId, score: number, time?: number) => void; onFullscreen: () => void };

function CoreShooter({ haptics, onExit, onResult, onFullscreen }: GameProps) {
  const canvasRef = useRef<HTMLCanvasElement>(null); const stateRef = useRef({ x: 0, score: 0, health: 100, ammo: 24, enemies: Array.from({ length: 8 }, (_, i) => ({ x: (i % 4 - 1.5) * .42, z: 1 + i * .48, alive: true })), running: true });
  const [hud, setHud] = useState({ score: 0, health: 100, ammo: 24 }); const [paused, setPaused] = useState(false);
  const shoot = useCallback(() => { const game = stateRef.current; if (!game.running || game.ammo <= 0) return; game.ammo--; const target = game.enemies.filter((enemy) => enemy.alive).sort((a, b) => a.z - b.z).find((enemy) => Math.abs(enemy.x - game.x) < .24); if (target) { target.alive = false; game.score += 100; if (haptics && navigator.vibrate) navigator.vibrate(14); } setHud({ score: game.score, health: game.health, ammo: game.ammo }); }, [haptics]);
  useEffect(() => { const canvas = canvasRef.current; if (!canvas) return; const context = canvas.getContext('2d'); if (!context) return; let frame = 0; let previous = performance.now(); const keys = new Set<string>(); const keyDown = (event: KeyboardEvent) => { if (event.key === ' ') { event.preventDefault(); shoot(); } keys.add(event.key.toLowerCase()); }; const keyUp = (event: KeyboardEvent) => keys.delete(event.key.toLowerCase()); window.addEventListener('keydown', keyDown); window.addEventListener('keyup', keyUp);
    const render = (now: number) => { const dt = Math.min(.04, (now - previous) / 1000); previous = now; const game = stateRef.current; if (!paused && game.running) { if (keys.has('a') || keys.has('arrowleft')) game.x = Math.max(-.72, game.x - dt); if (keys.has('d') || keys.has('arrowright')) game.x = Math.min(.72, game.x + dt); game.enemies.forEach((enemy) => { if (enemy.alive) enemy.z -= dt * .11; if (enemy.alive && enemy.z < .14) { enemy.alive = false; game.health -= 18; } }); if (game.enemies.every((enemy) => !enemy.alive)) { game.running = false; onResult('core-shooter', game.score + game.health * 5); } if (game.health <= 0) { game.running = false; onResult('core-shooter', game.score); } setHud({ score: game.score, health: Math.max(0, game.health), ammo: game.ammo }); }
      const ratio = Math.min(devicePixelRatio, 2); const width = canvas.clientWidth; const height = canvas.clientHeight; if (canvas.width !== width * ratio || canvas.height !== height * ratio) { canvas.width = width * ratio; canvas.height = height * ratio; context.setTransform(ratio, 0, 0, ratio, 0, 0); } context.clearRect(0, 0, width, height); const sky = context.createLinearGradient(0, 0, 0, height); sky.addColorStop(0, '#071022'); sky.addColorStop(.54, '#1b2c4a'); sky.addColorStop(.55, '#11141d'); sky.addColorStop(1, '#03050a'); context.fillStyle = sky; context.fillRect(0, 0, width, height); const horizon = height * .54; context.strokeStyle = 'rgba(84,220,255,.3)'; context.lineWidth = 1; for (let i = 0; i < 14; i++) { const depth = i / 13; const y = horizon + depth * depth * (height - horizon); context.beginPath(); context.moveTo(0, y); context.lineTo(width, y); context.stroke(); } for (let i = -7; i <= 7; i++) { context.beginPath(); context.moveTo(width / 2, horizon); context.lineTo(width / 2 + i * width * .13, height); context.stroke(); } game.enemies.filter((enemy) => enemy.alive && enemy.z < 4).sort((a, b) => b.z - a.z).forEach((enemy) => { const scale = 1 / Math.max(.24, enemy.z); const x = width / 2 + (enemy.x - game.x) * width * .38 * scale; const y = horizon + (height - horizon) * scale * .72; const size = Math.min(100, 22 * scale); context.fillStyle = '#ff4f68'; context.fillRect(x - size / 2, y - size, size, size); context.fillStyle = '#fff'; context.fillRect(x - size * .22, y - size * .7, size * .12, size * .12); context.fillRect(x + size * .1, y - size * .7, size * .12, size * .12); }); context.strokeStyle = '#8be9ff'; context.beginPath(); context.moveTo(width / 2 - 12, height / 2); context.lineTo(width / 2 + 12, height / 2); context.moveTo(width / 2, height / 2 - 12); context.lineTo(width / 2, height / 2 + 12); context.stroke(); frame = requestAnimationFrame(render); }; frame = requestAnimationFrame(render); return () => { cancelAnimationFrame(frame); window.removeEventListener('keydown', keyDown); window.removeEventListener('keyup', keyUp); }; }, [onResult, paused, shoot]);
  const move = (delta: number) => { stateRef.current.x = Math.max(-.72, Math.min(.72, stateRef.current.x + delta)); };
  return <div className="nova-game nova-core-shooter"><canvas ref={canvasRef} onPointerDown={shoot} /><header><span><Heart />{hud.health}</span><span><Crosshair />{hud.ammo}</span><strong>CORE SHOOTER</strong><span>{hud.score}</span><button type="button" onClick={() => setPaused(!paused)} aria-label={paused ? 'Продолжить игру' : 'Пауза'}>{paused ? <Play /> : <Pause />}</button><button type="button" onClick={onFullscreen} aria-label="Играть на весь экран"><Expand /></button></header><div className="nova-game-touch"><ModernTouchButton haptics={haptics} onPointerDown={() => move(-.12)} aria-label="Двигаться влево">◀</ModernTouchButton><ModernTouchButton className="is-fire" haptics={haptics} onPointerDown={shoot} aria-label="Стрелять"><Crosshair /></ModernTouchButton><ModernTouchButton haptics={haptics} onPointerDown={() => move(.12)} aria-label="Двигаться вправо">▶</ModernTouchButton></div>{!stateRef.current.running ? <div className="nova-game-result"><Trophy /><h2>Сигнал завершён</h2><strong>{hud.score} очков</strong><button type="button" onClick={onExit}>В библиотеку</button></div> : null}</div>;
}

type Cell = 0 | 1; type Piece = { cells: number[][]; x: number; y: number };
const shapes = [[[1, 1, 1, 1]], [[1, 1], [1, 1]], [[0, 1, 0], [1, 1, 1]], [[1, 0], [1, 0], [1, 1]], [[0, 1, 1], [1, 1, 0]]];
const newPiece = (): Piece => ({ cells: shapes[Math.floor(Math.random() * shapes.length)], x: 3, y: 0 });
function BlocksGame({ haptics, onExit, onResult, onFullscreen }: GameProps) {
  const [board, setBoard] = useState<Cell[][]>(() => Array.from({ length: 18 }, () => Array(10).fill(0))); const [piece, setPiece] = useState(newPiece); const [score, setScore] = useState(0); const [lines, setLines] = useState(0); const [paused, setPaused] = useState(false); const [over, setOver] = useState(false);
  const valid = useCallback((candidate: Piece, source = board) => candidate.cells.every((row, y) => row.every((value, x) => !value || (candidate.y + y >= 0 && candidate.y + y < 18 && candidate.x + x >= 0 && candidate.x + x < 10 && !source[candidate.y + y][candidate.x + x]))), [board]);
  const lock = useCallback(() => { const next = board.map((row) => [...row]); piece.cells.forEach((row, y) => row.forEach((value, x) => { if (value && piece.y + y >= 0) next[piece.y + y][piece.x + x] = 1; })); const remaining = next.filter((row) => row.some((cell) => !cell)); const cleared = 18 - remaining.length; const clearedBoard = [...Array.from({ length: cleared }, () => Array(10).fill(0) as Cell[]), ...remaining]; const spawned = newPiece(); setBoard(clearedBoard); setScore((value) => value + 20 + cleared * cleared * 100); setLines((value) => value + cleared); setPiece(spawned); if (!valid(spawned, clearedBoard)) { setOver(true); onResult('blocks', score + cleared * 100); } }, [board, onResult, piece, score, valid]);
  const move = useCallback((dx: number, dy: number) => { if (paused || over) return; const candidate = { ...piece, x: piece.x + dx, y: piece.y + dy }; if (valid(candidate)) setPiece(candidate); else if (dy > 0) lock(); }, [lock, over, paused, piece, valid]);
  const rotate = useCallback(() => { const cells = piece.cells[0].map((_, index) => piece.cells.map((row) => row[index]).reverse()); const candidate = { ...piece, cells }; if (valid(candidate)) setPiece(candidate); }, [piece, valid]);
  const drop = useCallback(() => { let candidate = { ...piece }; while (valid({ ...candidate, y: candidate.y + 1 })) candidate = { ...candidate, y: candidate.y + 1 }; setPiece(candidate); window.setTimeout(lock, 0); if (haptics && navigator.vibrate) navigator.vibrate(10); }, [haptics, lock, piece, valid]);
  useEffect(() => { const timer = window.setInterval(() => move(0, 1), Math.max(160, 650 - Math.floor(lines / 8) * 55)); return () => clearInterval(timer); }, [lines, move]);
  useEffect(() => { const handler = (event: KeyboardEvent) => { if (event.key === 'ArrowLeft') move(-1, 0); if (event.key === 'ArrowRight') move(1, 0); if (event.key === 'ArrowDown') move(0, 1); if (event.key === 'ArrowUp') rotate(); if (event.key === ' ') { event.preventDefault(); drop(); } }; window.addEventListener('keydown', handler); return () => window.removeEventListener('keydown', handler); }, [drop, move, rotate]);
  const cells = board.map((row) => [...row]); piece.cells.forEach((row, y) => row.forEach((value, x) => { if (value && piece.y + y < 18 && piece.x + x >= 0 && piece.x + x < 10) cells[piece.y + y][piece.x + x] = 1; }));
  return <div className="nova-game nova-blocks"><header><div><small>SCORE</small><strong>{score}</strong></div><div><small>LINES</small><strong>{lines}</strong></div><b>BLOCKS</b><button type="button" onClick={() => setPaused(!paused)} aria-label={paused ? 'Продолжить игру' : 'Пауза'}>{paused ? <Play /> : <Pause />}</button><button type="button" onClick={onFullscreen} aria-label="Играть на весь экран"><Expand /></button></header><main>{cells.flatMap((row, y) => row.map((value, x) => <i className={value ? 'is-filled' : ''} key={`${x}-${y}`} />))}</main><div className="nova-game-touch"><ModernTouchButton haptics={haptics} onPointerDown={() => move(-1, 0)} aria-label="Сдвинуть влево">◀</ModernTouchButton><ModernTouchButton haptics={haptics} onPointerDown={rotate} aria-label="Повернуть блок"><RotateCw /></ModernTouchButton><ModernTouchButton haptics={haptics} onPointerDown={() => move(1, 0)} aria-label="Сдвинуть вправо">▶</ModernTouchButton><ModernTouchButton className="is-wide" haptics={haptics} onPointerDown={drop} aria-label="Быстро опустить блок">DROP</ModernTouchButton></div>{over ? <div className="nova-game-result"><Trophy /><h2>Раунд завершён</h2><strong>{score} очков</strong><button type="button" onClick={onExit}>В библиотеку</button></div> : null}</div>;
}

function RacingGame({ haptics, onExit, onResult, onFullscreen }: GameProps) {
  const canvasRef = useRef<HTMLCanvasElement>(null); const data = useRef({ lane: 1, speed: 0, distance: 0, started: performance.now(), done: false }); const [hud, setHud] = useState({ speed: 0, lap: 0, time: 0 }); const [paused, setPaused] = useState(false);
  useEffect(() => { const canvas = canvasRef.current; if (!canvas) return; const ctx = canvas.getContext('2d'); if (!ctx) return; let raf = 0; let last = performance.now(); const keys = new Set<string>(); const down = (event: KeyboardEvent) => keys.add(event.key.toLowerCase()); const up = (event: KeyboardEvent) => keys.delete(event.key.toLowerCase()); window.addEventListener('keydown', down); window.addEventListener('keyup', up); const loop = (now: number) => { const dt = Math.min(.04, (now - last) / 1000); last = now; const game = data.current; if (!paused && !game.done) { if (keys.has('arrowup') || keys.has('w')) game.speed = Math.min(220, game.speed + 95 * dt); else game.speed = Math.max(0, game.speed - 35 * dt); if (keys.has('arrowdown') || keys.has('s')) game.speed = Math.max(0, game.speed - 130 * dt); if (keys.has('arrowleft') || keys.has('a')) game.lane = Math.max(0, game.lane - dt * 1.8); if (keys.has('arrowright') || keys.has('d')) game.lane = Math.min(2, game.lane + dt * 1.8); game.distance += game.speed * dt; const elapsed = (now - game.started) / 1000; if (game.distance >= 2400) { game.done = true; onResult('racing', Math.round(10000 - elapsed * 80), elapsed); if (haptics && navigator.vibrate) navigator.vibrate([20, 30, 20]); } setHud({ speed: Math.round(game.speed), lap: Math.min(100, Math.round(game.distance / 24)), time: elapsed }); }
      const ratio = Math.min(devicePixelRatio, 2), w = canvas.clientWidth, h = canvas.clientHeight; if (canvas.width !== w * ratio || canvas.height !== h * ratio) { canvas.width = w * ratio; canvas.height = h * ratio; ctx.setTransform(ratio, 0, 0, ratio, 0, 0); } const offset = game.distance % 80; ctx.fillStyle = '#071224'; ctx.fillRect(0, 0, w, h); ctx.fillStyle = '#162c35'; ctx.fillRect(0, h * .25, w, h * .75); ctx.beginPath(); ctx.moveTo(w * .43, h * .25); ctx.lineTo(w * .08, h); ctx.lineTo(w * .92, h); ctx.lineTo(w * .57, h * .25); ctx.closePath(); ctx.fillStyle = '#252a33'; ctx.fill(); ctx.strokeStyle = '#f4e9bb'; ctx.lineWidth = 4; for (let i = 0; i < 12; i++) { const y = h * .28 + ((i * 80 + offset) % (h * .72)); const scale = (y - h * .25) / (h * .75); ctx.beginPath(); ctx.moveTo(w * .5 - scale * 4, y); ctx.lineTo(w * .5 + scale * 4, y + 28 * scale); ctx.stroke(); } const carX = w * .36 + game.lane * w * .14; ctx.fillStyle = '#70e7ff'; ctx.fillRect(carX - 24, h - 82, 48, 68); ctx.fillStyle = '#10243d'; ctx.fillRect(carX - 16, h - 70, 32, 22); raf = requestAnimationFrame(loop); }; raf = requestAnimationFrame(loop); return () => { cancelAnimationFrame(raf); window.removeEventListener('keydown', down); window.removeEventListener('keyup', up); }; }, [haptics, onResult, paused]);
  const steer = (delta: number) => { data.current.lane = Math.max(0, Math.min(2, data.current.lane + delta)); }; const accelerate = () => { data.current.speed = Math.min(220, data.current.speed + 22); };
  return <div className="nova-game nova-racing"><canvas ref={canvasRef} /><header><span><Gauge />{hud.speed} км/ч</span><strong>NOVA CIRCUIT</strong><span><Flag />{hud.lap}%</span><time>{hud.time.toFixed(1)}s</time><button type="button" onClick={() => setPaused(!paused)} aria-label={paused ? 'Продолжить гонку' : 'Пауза'}>{paused ? <Play /> : <Pause />}</button><button type="button" onClick={onFullscreen} aria-label="Играть на весь экран"><Expand /></button></header><div className="nova-game-touch"><ModernTouchButton haptics={haptics} onPointerDown={() => steer(-.35)} aria-label="Повернуть влево">◀</ModernTouchButton><ModernTouchButton className="is-accelerate" haptics={haptics} onPointerDown={accelerate} aria-label="Ускорение"><Zap /></ModernTouchButton><ModernTouchButton haptics={haptics} onPointerDown={() => steer(.35)} aria-label="Повернуть вправо">▶</ModernTouchButton></div>{data.current.done ? <div className="nova-game-result"><Flag /><h2>Финиш</h2><strong>{hud.time.toFixed(2)} секунды</strong><button type="button" onClick={onExit}>В библиотеку</button></div> : null}</div>;
}

export function ModernGames({ state, haptics, onState, onFullscreen }: { state: ModernOsState; haptics: boolean; onState: (id: ModernGameId, score: number, time?: number) => void; onFullscreen: () => void }) {
  const [game, setGame] = useState<ModernGameId | null>(null); const props = { haptics, onExit: () => setGame(null), onResult: onState, onFullscreen };
  if (game === 'core-shooter') return <CoreShooter {...props} />; if (game === 'blocks') return <BlocksGame {...props} />; if (game === 'racing') return <RacingGame {...props} />;
  const entries: Array<{ id: ModernGameId; title: string; kicker: string; text: string; icon: typeof Shield }> = [{ id: 'core-shooter', title: 'CORE SHOOTER', kicker: 'FPS / SIGNAL', text: 'Оригинальный lightweight arena FPS без сторонних игровых assets.', icon: Shield }, { id: 'blocks', title: 'BLOCKS', kicker: 'LOGIC / FALLING', text: 'Классическая механика падающих блоков в собственной подаче SITEVL.', icon: Gamepad2 }, { id: 'racing', title: 'NOVA CIRCUIT', kicker: 'ARCADE / RACING', text: 'Короткая browser-native гонка на время.', icon: Flag }];
  return <div className="nova-game-library"><header><small>SITEVL GAME SYSTEM</small><h2>Игры</h2><p>Три оригинальных эксперимента. Прогресс и результаты хранятся локально.</p></header><section>{entries.map(({ id, title, kicker, text, icon: Icon }) => <article className={`is-${id}`} key={id}><div><Icon /></div><small>{kicker}</small><h3>{title}</h3><p>{text}</p><dl><span><dt>Запусков</dt><dd>{state.games[id].launches}</dd></span><span><dt>Рекорд</dt><dd>{state.games[id].highScore}</dd></span></dl><button type="button" onClick={() => setGame(id)}><Play />Играть</button></article>)}</section></div>;
}
