import { Expand, Flag, Gauge, Pause, Play, RotateCcw, Trophy, X, Zap } from 'lucide-react';
import { useCallback, useEffect, useRef, useState } from 'react';
import type { ModernGameProps } from './modernGameTypes';
import { ModernTouchButton } from './ModernTouchButton';

const tracks = [
  { name: 'PACIFIC LOOP', sky: '#07162b', accent: '#6de9ff', curve: (d: number) => Math.sin(d / 280) * .7 + Math.sin(d / 91) * .18, length: 2600 },
  { name: 'NEON PORT', sky: '#180d2f', accent: '#ff6ed4', curve: (d: number) => Math.sin(d / 170) * .8 - Math.cos(d / 390) * .35, length: 2900 },
];

export function ModernCircuitGame({ haptics, progress, onExit, onRestart, onResult, onFullscreen }: ModernGameProps) {
  const canvasRef = useRef<HTMLCanvasElement>(null); const [trackIndex, setTrackIndex] = useState(progress.progress >= 55 ? 1 : 0); const track = tracks[trackIndex];
  const stateRef = useRef({ x: 0, speed: 0, distance: 0, lap: 1, lapStarted: performance.now(), started: performance.now(), bestLap: Infinity, finished: false, collision: 0, score: 0 });
  const controls = useRef({ left: false, right: false, accelerate: false, brake: false });
  const [hud, setHud] = useState({ speed: 0, lap: 1, time: 0, best: progress.bestTime, checkpoint: 1 }); const [paused, setPaused] = useState(false);
  const finish = useCallback((elapsed: number) => { const state = stateRef.current; if (state.finished) return; state.finished = true; const score = Math.max(0, Math.round(24000 - elapsed * 110 + state.score)); onResult('racing', { score, completed: true, time: state.bestLap, playTime: elapsed, achievement: state.bestLap < 42 ? 'Идеальная траектория' : undefined, progress: trackIndex ? 100 : 55 }); if (haptics && navigator.vibrate) navigator.vibrate([20, 35, 24]); }, [haptics, onResult, trackIndex]);
  useEffect(() => {
    const canvas = canvasRef.current; const ctx = canvas?.getContext('2d'); if (!canvas || !ctx) return; let raf = 0; let last = performance.now(); let hudAt = 0; const keys = new Set<string>();
    const down = (event: KeyboardEvent) => { if (event.key.startsWith('Arrow')) event.preventDefault(); keys.add(event.key.toLowerCase()); }; const up = (event: KeyboardEvent) => keys.delete(event.key.toLowerCase()); window.addEventListener('keydown', down); window.addEventListener('keyup', up);
    const loop = (now: number) => { const dt = Math.min(.04, (now - last) / 1000); last = now; const state = stateRef.current; if (!paused && !state.finished) { const accelerate = keys.has('w') || keys.has('arrowup') || controls.current.accelerate; const brake = keys.has('s') || keys.has('arrowdown') || controls.current.brake; const steer = ((keys.has('d') || keys.has('arrowright') || controls.current.right) ? 1 : 0) - ((keys.has('a') || keys.has('arrowleft') || controls.current.left) ? 1 : 0); state.speed = accelerate ? Math.min(248, state.speed + 115 * dt) : Math.max(0, state.speed - 30 * dt); if (brake) state.speed = Math.max(0, state.speed - 180 * dt); state.x += steer * dt * (1.25 + state.speed / 180); state.x -= track.curve(state.distance) * dt * state.speed / 230 * .18; state.x = Math.max(-1.42, Math.min(1.42, state.x)); if (Math.abs(state.x) > .94 && state.speed > 90) { state.speed = Math.max(65, state.speed - 150 * dt); state.collision = .18; } state.collision = Math.max(0, state.collision - dt); state.distance += state.speed * dt; if (state.distance >= track.length) { state.distance -= track.length; const lapTime = (now - state.lapStarted) / 1000; state.bestLap = Math.min(state.bestLap, lapTime); state.lapStarted = now; state.score += Math.round(5000 - lapTime * 40); state.lap += 1; if (state.lap > 3) finish((now - state.started) / 1000); } if (now - hudAt > 90) { setHud({ speed: Math.round(state.speed), lap: Math.min(3, state.lap), time: (now - state.lapStarted) / 1000, best: Number.isFinite(state.bestLap) ? state.bestLap : progress.bestTime, checkpoint: Math.min(4, Math.floor(state.distance / track.length * 4) + 1) }); hudAt = now; } }
      drawRace(ctx, canvas, state, track, now); raf = requestAnimationFrame(loop); };
    raf = requestAnimationFrame(loop); return () => { cancelAnimationFrame(raf); window.removeEventListener('keydown', down); window.removeEventListener('keyup', up); };
  }, [finish, paused, progress.bestTime, track]);
  const hold = (key: keyof typeof controls.current, value: boolean) => { controls.current[key] = value; };
  return <div className="nova-game nova-racing"><canvas ref={canvasRef} aria-label="Трасса NOVA CIRCUIT" /><header><span><Gauge />{hud.speed} км/ч</span><strong>NOVA CIRCUIT</strong><span><Flag />Круг {hud.lap}/3</span><span>CP {hud.checkpoint}/4</span><time>{hud.time.toFixed(1)} с</time>{hud.best ? <span>Лучший {hud.best.toFixed(2)}</span> : null}<button type="button" onClick={() => setPaused(!paused)} aria-label="Пауза">{paused ? <Play /> : <Pause />}</button><button type="button" onClick={onRestart} aria-label="Начать заново"><RotateCcw /></button><button type="button" onClick={onFullscreen} aria-label="Играть на весь экран"><Expand /></button><button type="button" onClick={onExit} aria-label="Выйти в библиотеку"><X /></button></header><div className="nova-track-picker" aria-label="Выбор трассы">{tracks.map((item, index) => <button type="button" className={trackIndex === index ? 'is-active' : ''} disabled={stateRef.current.distance > 20} onClick={() => { setTrackIndex(index); onRestart(); }} key={item.name}>{item.name}</button>)}</div><div className="nova-game-touch nova-racing-controls"><ModernTouchButton onPointerDown={() => hold('left', true)} onPointerUp={() => hold('left', false)} onPointerCancel={() => hold('left', false)}>◀</ModernTouchButton><ModernTouchButton className="is-accelerate" haptics={haptics} onPointerDown={() => hold('accelerate', true)} onPointerUp={() => hold('accelerate', false)} onPointerCancel={() => hold('accelerate', false)}><Zap /></ModernTouchButton><ModernTouchButton aria-label="Тормоз" onPointerDown={() => hold('brake', true)} onPointerUp={() => hold('brake', false)} onPointerCancel={() => hold('brake', false)}><Pause /></ModernTouchButton><ModernTouchButton onPointerDown={() => hold('right', true)} onPointerUp={() => hold('right', false)} onPointerCancel={() => hold('right', false)}>▶</ModernTouchButton></div>{paused ? <div className="nova-game-result"><Pause /><h2>Гонка на паузе</h2><button type="button" onClick={() => setPaused(false)}>Продолжить</button><button type="button" onClick={onExit}>Вернуться в игровой центр</button></div> : null}{stateRef.current.finished ? <div className="nova-game-result"><Trophy /><h2>Три круга завершены</h2><strong>Лучший круг {stateRef.current.bestLap.toFixed(2)} с</strong><div><button type="button" onClick={onRestart}>Ещё заезд</button><button type="button" onClick={onExit}>В библиотеку</button></div></div> : null}</div>;
}

function drawRace(ctx: CanvasRenderingContext2D, canvas: HTMLCanvasElement, state: { x: number; speed: number; distance: number; collision: number }, track: typeof tracks[number], now: number) {
  const ratio = Math.min(devicePixelRatio, 2), w = canvas.clientWidth, h = canvas.clientHeight; if (canvas.width !== Math.round(w * ratio) || canvas.height !== Math.round(h * ratio)) { canvas.width = Math.round(w * ratio); canvas.height = Math.round(h * ratio); ctx.setTransform(ratio, 0, 0, ratio, 0, 0); }
  const gradient = ctx.createLinearGradient(0, 0, 0, h); gradient.addColorStop(0, track.sky); gradient.addColorStop(.48, '#163c55'); gradient.addColorStop(.49, '#132526'); gradient.addColorStop(1, '#07100d'); ctx.fillStyle = gradient; ctx.fillRect(0, 0, w, h);
  ctx.fillStyle = 'rgba(102,235,255,.35)'; for (let i = 0; i < 22; i += 1) { const x = (i * 137 + trackIndexSeed(track.name)) % w; const height = 18 + (i % 5) * 12; ctx.fillRect(x, h * .48 - height, 4 + (i % 4) * 6, height); }
  const horizon = h * .45; const curve = track.curve(state.distance) * w * .12; ctx.beginPath(); ctx.moveTo(w * .48 + curve, horizon); ctx.lineTo(w * .07, h); ctx.lineTo(w * .93, h); ctx.lineTo(w * .52 + curve, horizon); ctx.closePath(); ctx.fillStyle = '#252b35'; ctx.fill(); ctx.strokeStyle = '#f4f0d1'; ctx.lineWidth = 4;
  for (let i = 0; i < 13; i += 1) { const progress = ((i * 90 + state.distance * 2.4) % 1170) / 1170; const y = horizon + progress * progress * (h - horizon); const half = progress * w * .36; ctx.beginPath(); ctx.moveTo(w / 2 + curve * (1 - progress) - 3, y); ctx.lineTo(w / 2 + curve * (1 - progress) + 3, y + 18 * progress); ctx.stroke(); if (i % 2 === 0) { ctx.fillStyle = track.accent; ctx.fillRect(w / 2 - half - 8, y, 7, 12 + 12 * progress); ctx.fillRect(w / 2 + half + 1, y, 7, 12 + 12 * progress); } }
  const carX = w / 2 + state.x * w * .25 + Math.sin(now / 18) * state.collision * 18; const carY = h - Math.max(82, h * .13); ctx.save(); ctx.translate(carX, carY); ctx.fillStyle = track.accent; ctx.beginPath(); ctx.roundRect(-34, -58, 68, 78, 14); ctx.fill(); ctx.fillStyle = '#0a1726'; ctx.fillRect(-23, -44, 46, 24); ctx.fillStyle = '#ff4f61'; ctx.fillRect(-25, 4, 13, 6); ctx.fillRect(12, 4, 13, 6); ctx.restore();
}
const trackIndexSeed = (name: string) => name.length * 41;
