import { Expand, FileAudio2, FileVideo2, FolderOpen, ListMusic, Pause, Play, Repeat2, Shuffle, SkipBack, SkipForward, Volume2, VolumeX } from 'lucide-react';
import { useEffect, useMemo, useRef, useState, type DragEvent, type RefObject, type SyntheticEvent } from 'react';
import { getModernMediaKind, type ModernMediaKind } from './modernOsModel';
import { ModernTouchButton } from './ModernTouchButton';

type MediaItem = { id: string; file: File; url: string; kind: Exclude<ModernMediaKind, 'unsupported'> };

export function ModernMedia({ haptics, osVolume, onFullscreen }: { haptics: boolean; osVolume: number; onFullscreen: () => void }) {
  const inputRef = useRef<HTMLInputElement>(null); const mediaRef = useRef<HTMLMediaElement>(null); const urls = useRef<string[]>([]);
  const [items, setItems] = useState<MediaItem[]>([]); const [activeId, setActiveId] = useState(''); const [playing, setPlaying] = useState(false); const [muted, setMuted] = useState(false); const [shuffle, setShuffle] = useState(false); const [repeat, setRepeat] = useState(false); const [filter, setFilter] = useState<'all' | 'audio' | 'video'>('all'); const [volume, setVolume] = useState(.75); const [progress, setProgress] = useState(0); const [duration, setDuration] = useState(0); const [error, setError] = useState('');
  const visibleItems = useMemo(() => filter === 'all' ? items : items.filter((item) => item.kind === filter), [filter, items]);
  const active = visibleItems.find((item) => item.id === activeId);
  useEffect(() => () => { const media = mediaRef.current; if (media) { media.pause(); media.removeAttribute('src'); media.load(); } urls.current.forEach((url) => URL.revokeObjectURL(url)); urls.current = []; }, []);
  useEffect(() => { if (!active && visibleItems[0]) setActiveId(visibleItems[0].id); }, [active, visibleItems]);
  useEffect(() => { if (mediaRef.current) { mediaRef.current.volume = Math.max(0, Math.min(1, volume * osVolume)); mediaRef.current.muted = muted; } }, [muted, osVolume, volume]);

  const addFiles = (files: FileList | File[]) => {
    const accepted: MediaItem[] = []; const rejected: string[] = [];
    Array.from(files).slice(0, 25).forEach((file) => { const kind = getModernMediaKind(file); if (kind === 'unsupported') { rejected.push(file.name); return; } const url = URL.createObjectURL(file); urls.current.push(url); accepted.push({ id: `media-${Date.now()}-${accepted.length}`, file, url, kind }); });
    setItems((current) => [...current, ...accepted]); if (accepted[0]) setActiveId(accepted[0].id); setError(rejected.length ? `Не поддерживается: ${rejected.join(', ')}` : '');
  };
  const toggle = async () => { const media = mediaRef.current; if (!media) return; if (media.paused) { try { await media.play(); setPlaying(true); } catch { setError('Браузер не смог начать воспроизведение этого файла.'); } } else { media.pause(); setPlaying(false); } };
  const step = (delta: number) => { if (!visibleItems.length) return; const index = Math.max(0, visibleItems.findIndex((item) => item.id === active?.id)); const next = shuffle && visibleItems.length > 1 ? (index + 1 + Math.floor(Math.random() * (visibleItems.length - 1))) % visibleItems.length : (index + delta + visibleItems.length) % visibleItems.length; setActiveId(visibleItems[next].id); setPlaying(false); setProgress(0); };
  const selectFilter = (next: 'all' | 'audio' | 'video') => { mediaRef.current?.pause(); const candidates = next === 'all' ? items : items.filter((item) => item.kind === next); setFilter(next); setActiveId(candidates[0]?.id || ''); setPlaying(false); setProgress(0); };
  const ended = async () => { const media = mediaRef.current; if (repeat && media) { media.currentTime = 0; try { await media.play(); setPlaying(true); } catch { setPlaying(false); } return; } step(1); };
  const drop = (event: DragEvent) => { event.preventDefault(); addFiles(event.dataTransfer.files); };
  const mediaEvents = { onTimeUpdate: (event: SyntheticEvent<HTMLMediaElement>) => setProgress(event.currentTarget.currentTime), onLoadedMetadata: (event: SyntheticEvent<HTMLMediaElement>) => { setDuration(event.currentTarget.duration); setError(''); }, onPlay: () => setPlaying(true), onPause: () => setPlaying(false), onError: () => { setPlaying(false); setError('Формат файла выбран, но его кодек не поддерживается этим браузером.'); }, onEnded: () => { void ended(); } };

  return <div className="nova-media" onDragOver={(event) => event.preventDefault()} onDrop={drop}>
    <aside><header><ListMusic /><strong>Медиатека</strong><button type="button" onClick={() => inputRef.current?.click()}><FolderOpen />Добавить</button><input ref={inputRef} hidden type="file" accept="audio/*,video/*,.flac,.m4a,.mov" multiple onChange={(event) => { if (event.target.files) addFiles(event.target.files); event.target.value = ''; }} /></header><nav><button className={filter === 'all' ? 'is-active' : ''} type="button" onClick={() => selectFilter('all')}>Все</button><button className={filter === 'audio' ? 'is-active' : ''} type="button" onClick={() => selectFilter('audio')}>Аудио</button><button className={filter === 'video' ? 'is-active' : ''} type="button" onClick={() => selectFilter('video')}>Видео</button></nav><section>{visibleItems.map((item) => <button className={item.id === active?.id ? 'is-active' : ''} type="button" onClick={() => { mediaRef.current?.pause(); setActiveId(item.id); setPlaying(false); setProgress(0); }} key={item.id}>{item.kind === 'audio' ? <FileAudio2 /> : <FileVideo2 />}<span><strong>{item.file.name}</strong><small>{item.kind === 'audio' ? 'Аудио' : 'Видео'} · {(item.file.size / 1024 / 1024).toFixed(1)} MB</small></span></button>)}</section></aside>
    <main>{active ? <>
      <div className={`nova-media-stage is-${active.kind}`}>{active.kind === 'video' ? <video ref={mediaRef as RefObject<HTMLVideoElement>} src={active.url} {...mediaEvents} playsInline /> : <><div className="nova-media-cover"><FileAudio2 /></div><audio ref={mediaRef as RefObject<HTMLAudioElement>} src={active.url} {...mediaEvents} /></>}</div>
      <div className="nova-media-info"><small>{active.kind === 'audio' ? 'ЛОКАЛЬНОЕ АУДИО' : 'ЛОКАЛЬНОЕ ВИДЕО'}</small><h2>{active.file.name}</h2><p>Файл обрабатывается только в браузере и не загружается на сервер.</p></div>
      <div className="nova-media-progress"><span>{formatTime(progress)}</span><input aria-label="Позиция воспроизведения" type="range" min="0" max={duration || 1} step=".1" value={Math.min(progress, duration || 1)} onChange={(event) => { if (mediaRef.current) mediaRef.current.currentTime = Number(event.target.value); }} /><span>{formatTime(duration)}</span></div>
      <footer><ModernTouchButton className={shuffle ? 'is-active' : ''} haptics={haptics} onClick={() => setShuffle((value) => !value)} aria-label="Перемешать"><Shuffle /></ModernTouchButton><ModernTouchButton haptics={haptics} onClick={() => step(-1)} aria-label="Предыдущий файл"><SkipBack /></ModernTouchButton><ModernTouchButton className="is-play" haptics={haptics} onClick={toggle} aria-label={playing ? 'Пауза' : 'Воспроизвести'}>{playing ? <Pause /> : <Play />}</ModernTouchButton><ModernTouchButton haptics={haptics} onClick={() => step(1)} aria-label="Следующий файл"><SkipForward /></ModernTouchButton><ModernTouchButton className={repeat ? 'is-active' : ''} haptics={haptics} onClick={() => setRepeat((value) => !value)} aria-label="Повтор"><Repeat2 /></ModernTouchButton><ModernTouchButton haptics={haptics} onClick={() => setMuted((value) => !value)} aria-label={muted ? 'Включить звук' : 'Выключить звук'}>{muted ? <VolumeX /> : <Volume2 />}</ModernTouchButton><label><input aria-label="Громкость медиаплеера" type="range" min="0" max="1" step=".01" value={volume} onChange={(event) => setVolume(Number(event.target.value))} /></label><ModernTouchButton haptics={haptics} onClick={onFullscreen} aria-label="Медиаплеер на весь экран"><Expand /></ModernTouchButton></footer>
    </> : <div className="nova-media-empty"><div><FileAudio2 /><FileVideo2 /></div><h2>{items.length ? 'В этом разделе пока нет файлов' : 'SITEVL MEDIA'}</h2><p>{items.length ? `Добавьте ${filter === 'video' ? 'видео' : 'аудио'} или выберите другой раздел медиатеки.` : 'Перетащите MP3, AAC, WAV, FLAC, MP4, WebM или MOV. Поддержка конкретного кодека зависит от браузера.'}</p><button type="button" onClick={() => inputRef.current?.click()}><FolderOpen />Выбрать локальные файлы</button><small>Файлы не отправляются на сервер.</small></div>}{error ? <p className="nova-media-error">{error}</p> : null}</main>
  </div>;
}

function formatTime(value: number) { if (!Number.isFinite(value)) return '0:00'; const minutes = Math.floor(value / 60); return `${minutes}:${Math.floor(value % 60).toString().padStart(2, '0')}`; }
