import { AnimatePresence, motion, useReducedMotion } from 'framer-motion';
import { AppWindow, BatteryMedium, Bell, Bluetooth, Bot, CalendarDays, ChevronLeft, ChevronRight, CircleUserRound, Clapperboard, Command, CopyPlus, Expand, File, FilePlus2, Files, Folder, FolderPlus, Gamepad2, Globe2, Grid3X3, HardDrive, House, Image, Layers3, Lock, Mail, Maximize2, MessageSquareText, Minimize2, MonitorCog, Moon, Music2, Network, PanelTop, Play, Plus, Power, RotateCcw, RotateCw, Search, Settings, Sparkles, Sun, Terminal, Trash2, Volume2, Wifi, X } from 'lucide-react';
import { lazy, Suspense, useCallback, useEffect, useMemo, useRef, useState, type PointerEvent as ReactPointerEvent } from 'react';
import { LabShell } from '../core/LabShell';
import { unlockLabAchievement } from '../core/storage';
import { useLabState } from '../core/useLabState';
import {
  addModernBrowserTab, closeModernBrowserTab, closeModernWindow, createModernFile, duplicateModernBrowserTab, focusModernWindow, isModernCompactViewport, moveModernBrowserHistory, navigateModernTab, normalizeModernAiAction, normalizeModernOsState, openModernWindow, patchModernWindow, readModernOsState, recordModernGame, reopenModernBrowserTab, restoreModernFile, searchModernOs, trashModernFile, writeModernOsState,
  type ModernAiAction, type ModernAppId, type ModernGameId, type ModernOsState, type ModernWindow,
} from './modernOsModel';
import './modernOs.css';

const ModernGames = lazy(() => import('./ModernGames').then((module) => ({ default: module.ModernGames })));
const ModernMedia = lazy(() => import('./ModernMedia').then((module) => ({ default: module.ModernMedia })));
const ModernAi = lazy(() => import('./ModernAi').then((module) => ({ default: module.ModernAi })));

const appCatalog: Array<{ id: ModernAppId; label: string; icon: typeof Files; color: string }> = [
  { id: 'files', label: 'Файлы', icon: Files, color: '#58a8ff' }, { id: 'browser', label: 'Браузер', icon: Globe2, color: '#62d7ef' }, { id: 'mail', label: 'Почта', icon: Mail, color: '#5588ff' }, { id: 'notes', label: 'Заметки', icon: MessageSquareText, color: '#ffd45b' }, { id: 'calendar', label: 'Календарь', icon: CalendarDays, color: '#ff646e' }, { id: 'photos', label: 'Фото', icon: Image, color: '#e782ff' }, { id: 'music', label: 'Музыка', icon: Music2, color: '#ff6587' }, { id: 'games', label: 'Игры', icon: Gamepad2, color: '#795dff' }, { id: 'media', label: 'Медиа', icon: Clapperboard, color: '#ff496f' }, { id: 'ai', label: 'SITEVL AI', icon: Bot, color: '#23b9ce' }, { id: 'terminal', label: 'Терминал', icon: Terminal, color: '#30343e' }, { id: 'settings', label: 'Настройки', icon: Settings, color: '#8d96a7' }, { id: 'studio', label: 'SITEVL Studio', icon: Sparkles, color: '#735cff' }, { id: 'network', label: 'Сеть', icon: Network, color: '#38c993' }, { id: 'about', label: 'О системе', icon: MonitorCog, color: '#6175a3' },
];
const appById = Object.fromEntries(appCatalog.map((app) => [app.id, app])) as Record<ModernAppId, typeof appCatalog[number]>;

function updateState(setState: React.Dispatch<React.SetStateAction<ModernOsState>>, update: (state: ModernOsState) => ModernOsState) { setState((current) => normalizeModernOsState(update(current))); }

function AppIcon({ id, label = true }: { id: ModernAppId; label?: boolean }) { const app = appById[id]; const Icon = app.icon; return <span className="nova-app-icon-wrap"><i className={`nova-app-icon is-${id}`} style={{ '--app-color': app.color } as React.CSSProperties}><Icon /></i>{label ? <small>{app.label}</small> : null}</span>; }

function InternalWeb({ url }: { url: string }) {
  const pages: Record<string, { kicker: string; title: string; text: string; action?: { label: string; href: string } }> = {
    'sitevl://home': { kicker: 'SITEVL NETWORK', title: 'Добро пожаловать в NOVA', text: 'Внутренняя сеть работает без интернета. Откройте LAB, Studio или справку системы.', action: { label: 'Открыть SITEVL LAB', href: '/lab' } },
    'sitevl://lab': { kicker: 'EXPERIMENTS', title: 'SITEVL LAB', text: 'Восемь интерактивных экспериментов: конструктор, игры, физика, операционные системы и бесконечный холст.', action: { label: 'Перейти в LAB', href: '/lab' } },
    'sitevl://studio': { kicker: 'CREATE', title: 'SITEVL Studio', text: 'Визуальный конструктор многостраничных сайтов с локальным хранением проектов.', action: { label: 'Открыть Studio', href: '/studio/projects' } },
    'sitevl://ai': { kicker: 'ASSIST', title: 'SITEVL AI', text: 'Встроенный AI-клиент использует настроенный провайдер и не имитирует ответы, когда подключение отсутствует.' },
    'sitevl://games': { kicker: 'PLAY', title: 'SITEVL Games', text: 'CORE SHOOTER, BLOCKS и NOVA CIRCUIT запускаются локально и сохраняют результаты в этой виртуальной системе.' },
    'sitevl://about': { kicker: 'NOVA 1.0', title: 'Современная среда SITEVL', text: 'Самостоятельная браузерная desktop-система. Она не управляет вашим настоящим компьютером.' },
    'sitevl://help': { kicker: 'HELP CENTER', title: 'Управление NOVA', text: 'Открывайте приложения через Dock. Ctrl/Cmd + Space вызывает поиск, F3 открывает обзор окон.' },
  };
  const page = pages[url] || pages['sitevl://home'];
  return <article className="nova-web-page"><small>{page.kicker}</small><h2>{page.title}</h2><p>{page.text}</p>{page.action ? <a href={page.action.href}>{page.action.label}</a> : null}<div className="nova-web-orbit" aria-hidden="true"><i /><i /><i /></div></article>;
}

function FilesApp({ state, setState }: { state: ModernOsState; setState: React.Dispatch<React.SetStateAction<ModernOsState>> }) {
  const [folder, setFolder] = useState('documents'); const [query, setQuery] = useState('');
  const folders = state.files.filter((item) => item.kind === 'folder' && !item.deletedAt);
  const shown = state.files.filter((item) => folder === 'trash' ? item.deletedAt : item.parentId === folder && !item.deletedAt).filter((item) => item.name.toLocaleLowerCase('ru').includes(query.toLocaleLowerCase('ru')));
  return <div className="nova-files"><aside><strong>Избранное</strong>{folders.filter((item) => item.id !== 'drive').map((item) => <button className={folder === item.id ? 'is-active' : ''} type="button" onClick={() => setFolder(item.id)} key={item.id}><Folder />{item.name}</button>)}<button className={folder === 'trash' ? 'is-active' : ''} type="button" onClick={() => setFolder('trash')}><Trash2 />Корзина</button></aside><section><header><label><Search /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Поиск файлов" /></label><button type="button" onClick={() => updateState(setState, (current) => createModernFile(current, folder === 'trash' ? 'documents' : folder, 'Новая папка', 'folder'))} title="Новая папка"><FolderPlus /></button><button type="button" onClick={() => updateState(setState, (current) => createModernFile(current, folder === 'trash' ? 'documents' : folder, 'Новый документ.txt'))} title="Новый документ"><FilePlus2 /></button></header><div className="nova-files-grid">{shown.map((item) => <article key={item.id}><i>{item.kind === 'folder' ? <Folder /> : item.kind === 'image' ? <Image /> : <File />}</i><strong>{item.name}</strong><small>{item.kind === 'folder' ? 'Папка' : item.kind.toUpperCase()}</small><button type="button" onClick={() => updateState(setState, (current) => item.deletedAt ? restoreModernFile(current, item.id) : trashModernFile(current, item.id))}>{item.deletedAt ? 'Восстановить' : 'В корзину'}</button></article>)}</div>{shown.length === 0 ? <div className="nova-empty"><Folder /><strong>Здесь пока пусто</strong><span>Создайте папку или документ.</span></div> : null}</section></div>;
}

function BrowserApp({ state, setState, onFullscreen }: { state: ModernOsState; setState: React.Dispatch<React.SetStateAction<ModernOsState>>; onFullscreen: () => void }) {
  const active = state.browser.tabs.find((tab) => tab.id === state.browser.activeTabId) || state.browser.tabs[0]; const [input, setInput] = useState(active.url); const [error, setError] = useState('');
  useEffect(() => setInput(active.url), [active.url]);
  const go = () => { const result = navigateModernTab(state, active.id, input); setError(result.error || ''); setState(result.state); };
  const internal = active.url.startsWith('sitevl://');
  const canBack = active.historyIndex > 0; const canForward = active.historyIndex < active.history.length - 1;
  return <div className="nova-browser"><div className="nova-browser-tabs">{state.browser.tabs.map((tab) => <button className={tab.id === active.id ? 'is-active' : ''} type="button" onClick={() => setState({ ...state, browser: { ...state.browser, activeTabId: tab.id } })} key={tab.id}><span>{tab.title}</span><X onClick={(event) => { event.stopPropagation(); setState(closeModernBrowserTab(state, tab.id)); }} /></button>)}<button type="button" onClick={() => setState(addModernBrowserTab(state))} aria-label="Новая вкладка"><Plus /></button></div><form className="nova-browser-bar" onSubmit={(event) => { event.preventDefault(); go(); }}><button type="button" disabled={!canBack} onClick={() => setState(moveModernBrowserHistory(state, active.id, -1))} aria-label="Назад"><ChevronLeft /></button><button type="button" disabled={!canForward} onClick={() => setState(moveModernBrowserHistory(state, active.id, 1))} aria-label="Вперёд"><ChevronRight /></button><button type="button" onClick={go} aria-label="Обновить"><RotateCw /></button><button type="button" onClick={() => { setInput('sitevl://home'); const result = navigateModernTab(state, active.id, 'sitevl://home'); setState(result.state); }} aria-label="Домой"><House /></button><label><Lock /><input value={input} onChange={(event) => setInput(event.target.value)} aria-label="Адрес сайта" /></label><button type="button" onClick={() => setState(duplicateModernBrowserTab(state, active.id))} aria-label="Дублировать вкладку"><CopyPlus /></button><button type="button" disabled={!state.browser.recentlyClosed.length} onClick={() => setState(reopenModernBrowserTab(state))} aria-label="Открыть закрытую вкладку"><RotateCcw /></button><button type="button" onClick={onFullscreen} aria-label="Развернуть браузер"><Expand /></button></form>{error ? <p className="nova-browser-error">{error}</p> : null}<div className="nova-browser-view">{internal ? <InternalWeb url={active.url} /> : <><iframe key={active.url} src={active.url} title={active.title} sandbox="allow-forms allow-popups allow-same-origin allow-scripts" referrerPolicy="no-referrer" /><aside><span>Если страница остаётся пустой, сайт мог запретить встраивание через CSP или X-Frame-Options.</span><button type="button" onClick={() => window.open(active.url, '_blank', 'noopener,noreferrer')}>Открыть во внешнем браузере</button><button type="button" disabled={!canBack} onClick={() => setState(moveModernBrowserHistory(state, active.id, -1))}>Назад</button></aside></>}</div></div>;
}

function NotesApp({ state, setState }: { state: ModernOsState; setState: React.Dispatch<React.SetStateAction<ModernOsState>> }) {
  const [selected, setSelected] = useState(state.notes[0]?.id); const note = state.notes.find((item) => item.id === selected);
  const create = () => { const next = { id: `note-${Date.now()}`, title: 'Новая заметка', content: '', pinned: false, modifiedAt: new Date().toISOString() }; setState({ ...state, notes: [next, ...state.notes] }); setSelected(next.id); };
  return <div className="nova-notes"><aside><button type="button" onClick={create}><Plus />Новая заметка</button>{state.notes.map((item) => <button className={item.id === selected ? 'is-active' : ''} type="button" onClick={() => setSelected(item.id)} key={item.id}><strong>{item.title}</strong><small>{item.content.slice(0, 42) || 'Пустая заметка'}</small></button>)}</aside>{note ? <section><input value={note.title} onChange={(event) => setState({ ...state, notes: state.notes.map((item) => item.id === note.id ? { ...item, title: event.target.value, modifiedAt: new Date().toISOString() } : item) })} aria-label="Название заметки" /><textarea value={note.content} onChange={(event) => setState({ ...state, notes: state.notes.map((item) => item.id === note.id ? { ...item, content: event.target.value, modifiedAt: new Date().toISOString() } : item) })} aria-label="Текст заметки" /><small>Сохранено локально · {note.content.trim() ? note.content.trim().split(/\s+/).length : 0} слов</small></section> : null}</div>;
}

function SettingsApp({ state, setState }: { state: ModernOsState; setState: React.Dispatch<React.SetStateAction<ModernOsState>> }) {
  return <div className="nova-settings"><aside><CircleUserRound /><strong>{state.profileName}</strong><span>Виртуальный профиль</span>{['Оформление', 'Рабочий стол', 'Dock', 'Control Center', 'Звук', 'Уведомления', 'Дисплей', 'Хранилище', 'Конфиденциальность'].map((item) => <button type="button" key={item}>{item}</button>)}</aside><section><small>ОФОРМЛЕНИЕ</small><h2>Сделайте NOVA своей</h2><div className="nova-setting-group"><strong>Режим</strong><div className="nova-segments">{(['light', 'dark', 'auto'] as const).map((theme) => <button className={state.theme === theme ? 'is-active' : ''} type="button" onClick={() => setState({ ...state, theme })} key={theme}>{theme === 'light' ? 'Светлая' : theme === 'dark' ? 'Тёмная' : 'Авто'}</button>)}</div></div><div className="nova-setting-group"><strong>Фон</strong><div className="nova-wallpapers">{(['aurora', 'ocean', 'midnight', 'glass', 'vladivostok'] as const).map((wallpaper) => <button className={`wallpaper-${wallpaper} ${state.wallpaper === wallpaper ? 'is-active' : ''}`} type="button" onClick={() => setState({ ...state, wallpaper })} aria-label={wallpaper} key={wallpaper} />)}</div></div><label className="nova-slider">Яркость <input type="range" min="35" max="100" value={state.brightness} onChange={(event) => setState({ ...state, brightness: Number(event.target.value) })} /><span>{state.brightness}%</span></label><label className="nova-toggle"><span><strong>Уменьшить прозрачность</strong><small>Делает материалы плотнее и контрастнее.</small></span><input type="checkbox" checked={state.reducedTransparency} onChange={(event) => setState({ ...state, reducedTransparency: event.target.checked })} /></label></section></div>;
}

function TerminalApp({ state, openApp, onFullscreen }: { state: ModernOsState; openApp: (id: ModernAppId) => void; onFullscreen: () => void }) {
  const [lines, setLines] = useState(['SITEVL NOVA Terminal 1.0', 'Введите help для списка команд.']); const [input, setInput] = useState('');
  const run = () => { const parts = input.trim().split(/\s+/); const command = parts[0]?.toLowerCase(); let output = ''; if (command === 'help') output = 'help · ls · pwd · cat · clear · echo · date · whoami · open · apps · games · ai · browser · fullscreen · network · systeminfo · lab'; else if (command === 'ls') output = state.files.filter((item) => item.parentId === 'documents' && !item.deletedAt).map((item) => item.name).join('   '); else if (command === 'pwd') output = '/SITEVL Drive/Documents'; else if (command === 'date') output = new Date().toLocaleString('ru-RU'); else if (command === 'whoami') output = state.profileName; else if (command === 'systeminfo') output = 'SITEVL NOVA 2.0 · виртуальная система · React renderer'; else if (command === 'network') output = 'SITEVL-NET: online · DESK95-PC · CLASSIC-DESK · MONO-STATION'; else if (command === 'apps') output = appCatalog.map((app) => app.id).join('  '); else if (command === 'games' || command === 'ai' || command === 'browser') { openApp(command === 'games' ? 'games' : command === 'ai' ? 'ai' : 'browser'); output = `Открываю ${command}`; } else if (command === 'fullscreen') { onFullscreen(); output = 'Переключаю полноэкранный режим'; } else if (command === 'echo') output = parts.slice(1).join(' '); else if (command === 'open' && appById[parts[1] as ModernAppId]) { openApp(parts[1] as ModernAppId); output = `Открываю ${parts[1]}`; } else if (command === 'lab') { window.location.href = '/lab'; output = 'Переход в SITEVL LAB'; } else if (command === 'clear') { setLines([]); setInput(''); return; } else output = command ? `Команда не найдена: ${command}` : ''; setLines([...lines, `nova % ${input}`, output]); setInput(''); };
  return <div className="nova-terminal"><div>{lines.map((line, index) => <p key={`${line}-${index}`}>{line}</p>)}</div><form onSubmit={(event) => { event.preventDefault(); run(); }}><span>nova %</span><input autoFocus value={input} onChange={(event) => setInput(event.target.value)} aria-label="Команда терминала" /></form></div>;
}

function GenericApp({ id, state }: { id: ModernAppId; state: ModernOsState }) {
  if (id === 'mail') return <div className="nova-mail"><aside><button type="button"><Plus />Новое письмо</button>{['Входящие  2', 'Помеченные', 'Черновики', 'Отправленные', 'Корзина'].map((item) => <span key={item}>{item}</span>)}</aside><section><article><b>SV</b><div><strong>Добро пожаловать в NOVA</strong><p>Ваша виртуальная система готова. Все сообщения являются локальной демонстрацией.</p></div><time>сегодня</time></article><article><b>LAB</b><div><strong>Новый эксперимент</strong><p>Modern OS добавлена в каталог SITEVL LAB.</p></div><time>сегодня</time></article></section></div>;
  if (id === 'calendar') return <div className="nova-calendar"><header><small>{new Date().toLocaleString('ru-RU', { month: 'long', year: 'numeric' })}</small><h2>{new Date().getDate()}</h2><span>Сегодня</span></header><div>{Array.from({ length: 35 }, (_, index) => <i className={index + 1 === new Date().getDate() ? 'is-today' : ''} key={index}>{index < 31 ? index + 1 : ''}</i>)}</div><aside><strong>События</strong><span><i />Исследовать SITEVL LAB · 18:00</span><button type="button"><Plus />Добавить событие</button></aside></div>;
  if (id === 'photos') return <div className="nova-photos"><header><h2>Фото</h2><button type="button">Импортировать</button></header><div>{['aurora', 'ocean', 'glass', 'vladivostok', 'midnight', 'ocean'].map((name, index) => <article className={`wallpaper-${name}`} key={`${name}-${index}`}><span>{index + 1}</span></article>)}</div><p>Изображения устройства доступны только после явного выбора файла.</p></div>;
  if (id === 'music') return <div className="nova-music"><div className="nova-album"><Music2 /></div><small>SITEVL DEMO AUDIO</small><h2>Night Signal</h2><p>Встроенная визуальная демонстрация · звук не загружен</p><input type="range" value="0" readOnly /><div><button type="button"><ChevronLeft /></button><button type="button"><Play /></button><button type="button"><ChevronRight /></button></div></div>;
  if (id === 'studio') return <div className="nova-studio-app"><Sparkles /><small>SITEVL CREATIVE SYSTEM</small><h2>Studio</h2><p>Создавайте многостраничные сайты из готовых компонентов и редактируйте результат визуально.</p><a href="/studio/projects">Открыть конструктор</a></div>;
  if (id === 'network') return <div className="nova-network"><header><Network /><div><h2>Сеть SITEVL</h2><p>Виртуальная сеть не сканирует реальные устройства.</p></div></header>{['DESK95-PC', 'CLASSIC-DESK', 'MONO-STATION'].map((name) => <article key={name}><i /><HardDrive /><span><strong>{name}</strong><small>Retro shared computer · в сети</small></span><button type="button">Общие файлы</button></article>)}</div>;
  return <div className="nova-about"><div className="nova-glyph">N</div><small>VERSION 1.0 · BROWSER EDITION</small><h2>SITEVL NOVA</h2><p>Современная виртуальная desktop-среда SITEVL. Все файлы, показатели и устройства внутри неё являются частью симуляции.</p><dl><div><dt>Renderer</dt><dd>{navigator.userAgent.includes('Safari') ? 'WebKit-compatible' : 'Browser renderer'}</dd></div><div><dt>WebGL</dt><dd>{document.createElement('canvas').getContext('webgl') ? 'Доступен' : 'Недоступен'}</dd></div><div><dt>WebGPU</dt><dd>{'gpu' in navigator ? 'Доступен' : 'Недоступен'}</dd></div><div><dt>Окон</dt><dd>{state.windows.length}</dd></div></dl></div>;
}

type AppContentProps = { window: ModernWindow; state: ModernOsState; setState: React.Dispatch<React.SetStateAction<ModernOsState>>; openApp: (id: ModernAppId) => void; onFullscreen: (windowId: string) => void; onGameResult: (id: ModernGameId, score: number, time?: number) => void; onAiAction: (action: ModernAiAction) => void };

function AppContent({ window, state, setState, openApp, onFullscreen, onGameResult, onAiAction }: AppContentProps) {
  if (window.appId === 'files') return <FilesApp state={state} setState={setState} />;
  if (window.appId === 'browser') return <BrowserApp state={state} setState={setState} onFullscreen={() => onFullscreen(window.id)} />;
  if (window.appId === 'notes') return <NotesApp state={state} setState={setState} />;
  if (window.appId === 'settings') return <SettingsApp state={state} setState={setState} />;
  if (window.appId === 'terminal') return <TerminalApp state={state} openApp={openApp} onFullscreen={() => onFullscreen(window.id)} />;
  if (window.appId === 'games') return <Suspense fallback={<div className="nova-app-loading"><Gamepad2 /><span>Загружаю игры…</span></div>}><ModernGames state={state} haptics={!state.lowPowerMode} onState={onGameResult} onFullscreen={() => onFullscreen(window.id)} /></Suspense>;
  if (window.appId === 'media') return <Suspense fallback={<div className="nova-app-loading"><Clapperboard /><span>Загружаю медиаплеер…</span></div>}><ModernMedia haptics={!state.lowPowerMode} onFullscreen={() => onFullscreen(window.id)} /></Suspense>;
  if (window.appId === 'ai') return <Suspense fallback={<div className="nova-app-loading"><Bot /><span>Загружаю SITEVL AI…</span></div>}><ModernAi state={state} onAction={onAiAction} onFullscreen={() => onFullscreen(window.id)} /></Suspense>;
  return <GenericApp id={window.appId} state={state} />;
}

function ModernWindowView({ window, state, setState, openApp, onFullscreen, onGameResult, onAiAction, immersive }: AppContentProps & { immersive: boolean }) {
  const drag = useRef<{ x: number; y: number; startX: number; startY: number } | null>(null);
  const viewportWidth = globalThis.window.innerWidth; const renderedWidth = Math.min(window.width, Math.max(320, viewportWidth - 30)); const renderedX = Math.max(0, Math.min(window.x, viewportWidth - renderedWidth - 15));
  const beginDrag = (event: ReactPointerEvent) => { if (window.maximized || isModernCompactViewport(viewportWidth)) return; drag.current = { x: renderedX, y: window.y, startX: event.clientX, startY: event.clientY }; event.currentTarget.setPointerCapture(event.pointerId); };
  const move = (event: ReactPointerEvent) => { if (!drag.current) return; const x = Math.max(0, drag.current.x + event.clientX - drag.current.startX); const y = Math.max(42, drag.current.y + event.clientY - drag.current.startY); updateState(setState, (current) => patchModernWindow(current, window.id, { x, y })); };
  const stop = () => { drag.current = null; };
  return <motion.section className={`nova-window ${window.maximized ? 'is-maximized' : ''} ${immersive ? 'is-app-immersive' : ''}`} style={{ left: renderedX, top: window.y, width: renderedWidth, height: window.height, zIndex: window.z }} initial={{ opacity: 0, scale: .94, y: 16 }} animate={{ opacity: window.minimized ? 0 : 1, scale: window.minimized ? .4 : 1, y: window.minimized ? 400 : 0 }} exit={{ opacity: 0, scale: .92 }} transition={{ duration: .2 }} onPointerDown={() => updateState(setState, (current) => focusModernWindow(current, window.id))}><header onPointerDown={beginDrag} onPointerMove={move} onPointerUp={stop} onPointerCancel={stop}><div className="nova-window-controls"><button type="button" onClick={() => updateState(setState, (current) => closeModernWindow(current, window.id))} aria-label="Закрыть"><X /></button><button type="button" onClick={() => updateState(setState, (current) => patchModernWindow(current, window.id, { minimized: true }))} aria-label="Свернуть"><Minimize2 /></button><button type="button" onClick={() => updateState(setState, (current) => patchModernWindow(current, window.id, { maximized: !window.maximized }))} aria-label={window.maximized ? 'Восстановить' : 'Развернуть'}><Maximize2 /></button></div><AppIcon id={window.appId} label={false} /><strong>{window.title}</strong><button className="nova-window-menu" type="button" onClick={() => onFullscreen(window.id)} aria-label={immersive ? 'Выйти из режима приложения на весь экран' : 'Приложение на весь экран'}>{immersive ? <X /> : <Expand />}</button></header><div className="nova-window-content"><AppContent window={window} state={state} setState={setState} openApp={openApp} onFullscreen={onFullscreen} onGameResult={onGameResult} onAiAction={onAiAction} /></div></motion.section>;
}

export function ModernOsPage() {
  const reducedMotion = useReducedMotion(); const { state: labState } = useLabState('modern-os');
  const [state, setState] = useState(readModernOsState); const [booting, setBooting] = useState(!state.booted); const [clock, setClock] = useState(new Date()); const [control, setControl] = useState(false); const [notifications, setNotifications] = useState(false); const [search, setSearch] = useState(false); const [searchQuery, setSearchQuery] = useState(''); const [overview, setOverview] = useState(false); const [poweredOff, setPoweredOff] = useState(false); const [immersive, setImmersive] = useState(false); const [immersiveAppId, setImmersiveAppId] = useState<string | null>(null);
  const desktopRef = useRef<HTMLDivElement>(null); const gestureRef = useRef<{ y: number; touch: boolean } | null>(null); const nativeFullscreenRef = useRef(false);
  const dark = state.theme === 'dark' || (state.theme === 'auto' && matchMedia('(prefers-color-scheme: dark)').matches);
  useEffect(() => { writeModernOsState(state); }, [state]);
  useEffect(() => { unlockLabAchievement('MODERN_OS_USER'); const timer = window.setInterval(() => setClock(new Date()), 30_000); const boot = window.setTimeout(() => { setBooting(false); setState((current) => ({ ...current, booted: true })); }, reducedMotion ? 100 : 1250); return () => { clearInterval(timer); clearTimeout(boot); }; }, [reducedMotion]);
  useEffect(() => { if (state.windows.length >= 3) unlockLabAchievement('MODERN_MULTITASKER'); }, [state.windows.length]);
  const openApp = useCallback((id: ModernAppId) => { updateState(setState, (current) => openModernWindow(current, id, appById[id].label)); setSearch(false); setOverview(false); if (id === 'network') unlockLabAchievement('MODERN_EXPLORER'); }, []);
  const enterFullscreen = useCallback(() => { setImmersive(true); if (navigator.vibrate) navigator.vibrate(12); window.setTimeout(() => { if (!document.fullscreenElement) setImmersive(true); }, 250); if (desktopRef.current?.requestFullscreen && !document.fullscreenElement) void desktopRef.current.requestFullscreen().then(() => { nativeFullscreenRef.current = document.fullscreenElement === desktopRef.current; }).catch(() => { nativeFullscreenRef.current = false; }); }, []);
  const exitFullscreen = useCallback(async () => { setImmersive(false); setImmersiveAppId(null); try { if (document.fullscreenElement) await document.exitFullscreen(); } catch { /* The CSS fallback still exits. */ } finally { nativeFullscreenRef.current = false; } }, []);
  const toggleFullscreen = useCallback(() => { if (immersive || document.fullscreenElement) void exitFullscreen(); else enterFullscreen(); }, [enterFullscreen, exitFullscreen, immersive]);
  const toggleAppFullscreen = useCallback((windowId: string) => setImmersiveAppId((current) => current === windowId ? null : windowId), []);
  const onGameResult = useCallback((id: ModernGameId, score: number, time?: number) => { updateState(setState, (current) => recordModernGame(current, id, score, time)); unlockLabAchievement('MODERN_FIRST_GAME'); if (id === 'core-shooter') unlockLabAchievement('MODERN_CORE_COMPLETE'); if (id === 'blocks' && score >= 100) unlockLabAchievement('MODERN_BLOCKS_100'); if (id === 'racing' && time !== undefined && time < 45) unlockLabAchievement('MODERN_BEST_LAP'); }, []);
  const onAiAction = useCallback((candidate: ModernAiAction) => { const action = normalizeModernAiAction(candidate); if (!action) return; if (action.type === 'OPEN_APP') openApp(action.appId); else if (action.type === 'CLOSE_APP') setState((current) => ({ ...current, windows: current.windows.filter((item) => item.appId !== action.appId) })); else if (action.type === 'OPEN_SETTINGS') openApp('settings'); else if (action.type === 'SET_THEME') setState((current) => ({ ...current, theme: action.value })); else if (action.type === 'SET_VOLUME') setState((current) => ({ ...current, sound: action.value })); else if (action.type === 'OPEN_GAME') openApp('games'); else if (action.type === 'ENTER_FULLSCREEN') void enterFullscreen(); else if (action.type === 'EXIT_FULLSCREEN') void exitFullscreen(); }, [enterFullscreen, exitFullscreen, openApp]);
  useEffect(() => { const changed = () => { if (document.fullscreenElement === desktopRef.current) { nativeFullscreenRef.current = true; setImmersive(true); } else if (!document.fullscreenElement && nativeFullscreenRef.current) { nativeFullscreenRef.current = false; setImmersive(false); } }; document.addEventListener('fullscreenchange', changed); return () => document.removeEventListener('fullscreenchange', changed); }, []);
  useEffect(() => { const keyboard = (event: KeyboardEvent) => { if ((event.ctrlKey || event.metaKey) && event.code === 'Space') { event.preventDefault(); setSearch((current) => !current); } else if (event.key === 'Escape') { setSearch(false); setOverview(false); setControl(false); setNotifications(false); setImmersiveAppId(null); } else if (event.key === 'F3') { event.preventDefault(); setOverview((current) => !current); } else if ((event.ctrlKey || event.metaKey) && event.key.toLowerCase() === 'w') { const top = state.windows.filter((item) => item.space === state.activeSpace).sort((a, b) => b.z - a.z)[0]; if (top) setState((current) => closeModernWindow(current, top.id)); } }; window.addEventListener('keydown', keyboard); return () => window.removeEventListener('keydown', keyboard); }, [state.activeSpace, state.windows]);
  const results = useMemo(() => searchModernOs(state, searchQuery, appCatalog), [searchQuery, state]);
  const visibleWindows = state.windows.filter((item) => item.space === state.activeSpace && !item.minimized);
  if (poweredOff) return <LabShell experimentId="modern-os" title="SITEVL NOVA" description="Современная виртуальная desktop-система SITEVL." canonicalPath="/lab/modern-os" status="ИНТЕРАКТИВНО · MODERN OS" immersive className="nova-host"><div className="nova-power-off"><div className="nova-glyph">N</div><strong>Система выключена</strong><button type="button" onClick={() => { setPoweredOff(false); setBooting(true); window.setTimeout(() => setBooting(false), 900); }}><Power />Включить SITEVL NOVA</button></div></LabShell>;
  return <LabShell experimentId="modern-os" title="SITEVL NOVA" description="Современная виртуальная desktop-система SITEVL с окнами, файлами, браузером и локальным сохранением." canonicalPath="/lab/modern-os" status="ИНТЕРАКТИВНО · MODERN OS" immersive className={`nova-host is-${dark ? 'dark' : 'light'} wallpaper-${state.wallpaper} accent-${state.accent} ${state.reducedTransparency ? 'reduce-transparency' : ''} ${state.lowPowerMode ? 'is-low-power' : ''} ${immersive ? 'nova-immersive' : ''} ${immersiveAppId ? 'has-app-immersive' : ''}`}>
    <div ref={desktopRef} className="nova-desktop" style={{ '--nova-brightness': state.brightness } as React.CSSProperties} onContextMenu={(event) => event.preventDefault()} onPointerDown={(event) => { if (event.pointerType === 'touch' && event.clientY > window.innerHeight - 110) gestureRef.current = { y: event.clientY, touch: true }; }} onPointerUp={(event) => { if (gestureRef.current?.touch && gestureRef.current.y - event.clientY > 70) setOverview(true); gestureRef.current = null; }}>
      <AnimatePresence>{booting ? <motion.div className="nova-boot" initial={{ opacity: 1 }} exit={{ opacity: 0 }}><div className="nova-glyph">N</div><strong>SITEVL NOVA</strong><i /><button type="button" onClick={() => setBooting(false)}>Пропустить</button></motion.div> : null}</AnimatePresence>
      {state.locked ? <div className="nova-lock"><div>{clock.toLocaleTimeString('ru-RU', { hour: '2-digit', minute: '2-digit' })}</div><strong>{clock.toLocaleDateString('ru-RU', { weekday: 'long', day: 'numeric', month: 'long' })}</strong><p>{state.notifications.length} уведомления</p><button type="button" onClick={() => setState({ ...state, locked: false })}><CircleUserRound />Войти как {state.profileName}</button></div> : <>
        <header className="nova-menu-bar"><button type="button" onClick={() => setSearch(true)}><span className="nova-mark">N</span><strong>SITEVL</strong></button><span>{visibleWindows.sort((a, b) => b.z - a.z)[0]?.title || 'NOVA'}</span><div className="nova-app-menus"><button type="button">Файл</button><button type="button">Правка</button><button type="button">Вид</button><button type="button">Окно</button><button type="button">Справка</button></div><nav><button type="button" onClick={() => openApp('ai')} aria-label="Открыть SITEVL AI" title="SITEVL AI"><Bot /></button><button type="button" aria-label="Виртуальная сеть"><Wifi /></button><button type="button" aria-label="Звук"><Volume2 /></button><button type="button" aria-label="Виртуальная батарея" title="Виртуальная батарея системы"><BatteryMedium /></button><button type="button" onClick={() => setNotifications(!notifications)} className="nova-clock-button"><time>{clock.toLocaleTimeString('ru-RU', { hour: '2-digit', minute: '2-digit' })}</time></button><button type="button" onClick={() => setNotifications(!notifications)} aria-label="Уведомления"><Bell /><i>{state.notifications.length}</i></button><button type="button" onClick={() => setControl(!control)} aria-label="Пункт управления"><PanelTop /></button></nav></header>
        <main className="nova-workspace"><section className="nova-desktop-icons"><button type="button" onDoubleClick={() => openApp('files')} onClick={() => openApp('files')}><AppIcon id="files" /><span>SITEVL Drive</span></button><button type="button" onClick={() => openApp('network')}><AppIcon id="network" /><span>Сеть</span></button><button type="button" onClick={() => openApp('studio')}><AppIcon id="studio" /><span>Studio</span></button></section><aside className="nova-widgets"><article><small>СЕГОДНЯ</small><strong>{clock.getDate()}</strong><span>{clock.toLocaleDateString('ru-RU', { weekday: 'long', month: 'long' })}</span></article><article><small>SITEVL LAB</small><strong>Уровень {Math.min(10, Math.floor(labState.xp / 250) + 1)}</strong><span>{labState.explored.length}/8 экспериментов · {Object.keys(labState.achievements).length} достижений</span><a href="/lab">Открыть LAB</a></article></aside>
          <AnimatePresence>{visibleWindows.map((window) => <ModernWindowView key={window.id} window={window} state={state} setState={setState} openApp={openApp} onFullscreen={toggleAppFullscreen} onGameResult={onGameResult} onAiAction={onAiAction} immersive={immersiveAppId === window.id} />)}</AnimatePresence>
        </main>
        <footer className="nova-dock" aria-label="Dock SITEVL NOVA"><button type="button" onClick={() => setSearch(true)} aria-label="Приложения"><Grid3X3 /></button>{state.dock.map((id) => <button type="button" draggable onDragStart={(event) => event.dataTransfer.setData('text/plain', id)} onDragOver={(event) => event.preventDefault()} onDrop={(event) => { const source = event.dataTransfer.getData('text/plain') as ModernAppId; if (!state.dock.includes(source) || source === id) return; const dock = [...state.dock]; const from = dock.indexOf(source); const to = dock.indexOf(id); dock.splice(from, 1); dock.splice(to, 0, source); setState({ ...state, dock }); }} onClick={() => openApp(id)} title={appById[id].label} key={id}><AppIcon id={id} label={false} />{state.windows.some((window) => window.appId === id) ? <i /> : null}</button>)}{state.recentApps.filter((id) => !state.dock.includes(id)).slice(0, 2).length ? <span className="nova-dock-divider" /> : null}{state.recentApps.filter((id) => !state.dock.includes(id)).slice(0, 2).map((id) => <button type="button" onClick={() => openApp(id)} title={`Недавнее: ${appById[id].label}`} key={`recent-${id}`}><AppIcon id={id} label={false} /></button>)}<span className="nova-dock-divider" /><button type="button" onClick={() => openApp('files')} aria-label="Корзина"><Trash2 /></button><button type="button" onClick={() => setOverview(true)} aria-label="Обзор окон"><Layers3 /></button></footer>
      </>}
      <AnimatePresence>{control ? <motion.aside className="nova-control-center" initial={{ opacity: 0, y: -10, scale: .98 }} animate={{ opacity: 1, y: 0, scale: 1 }} exit={{ opacity: 0, y: -10, scale: .98 }}><header><strong>Пункт управления</strong><button type="button" onClick={() => setControl(false)} aria-label="Закрыть"><X /></button></header><div className="nova-control-grid"><button type="button" className="is-active"><Wifi /><span><strong>Сеть</strong><small>SITEVL-NET</small></span></button><button type="button"><Bluetooth /><span><strong>Bluetooth</strong><small>Виртуальная функция</small></span></button><button type="button"><Moon /><span><strong>Фокус</strong><small>Выключен</small></span></button><button type="button" onClick={() => setState({ ...state, theme: dark ? 'light' : 'dark' })}>{dark ? <Sun /> : <Moon />}<span><strong>Оформление</strong><small>{dark ? 'Тёмное' : 'Светлое'}</small></span></button><button type="button" onClick={() => openApp('ai')}><Bot /><span><strong>SITEVL AI</strong><small>Открыть помощника</small></span></button><button type="button" onClick={toggleFullscreen}><Expand /><span><strong>{immersive ? 'Выйти из полного экрана' : 'На весь экран'}</strong><small>{document.fullscreenEnabled ? 'Fullscreen API' : 'Режим совместимости'}</small></span></button><button type="button" className={state.lowPowerMode ? 'is-active' : ''} onClick={() => setState({ ...state, lowPowerMode: !state.lowPowerMode })}><BatteryMedium /><span><strong>Энергосбережение</strong><small>{state.lowPowerMode ? 'Включено' : 'Выключено'}</small></span></button></div><label><Sun /><input type="range" min="35" max="100" value={state.brightness} onChange={(event) => setState({ ...state, brightness: Number(event.target.value) })} /></label><label><Volume2 /><input type="range" min="0" max="100" value={state.sound} onChange={(event) => setState({ ...state, sound: Number(event.target.value) })} /></label><footer><button type="button" onClick={toggleFullscreen}><Expand />{immersive ? 'Выйти из полного экрана' : 'На весь экран'}</button><button type="button" onClick={() => setState({ ...state, locked: true })}><Lock />Заблокировать</button><button type="button" onClick={() => setPoweredOff(true)}><Power />Выключить</button></footer></motion.aside> : null}</AnimatePresence>
      <AnimatePresence>{notifications ? <motion.aside className="nova-notifications" initial={{ opacity: 0, x: 24 }} animate={{ opacity: 1, x: 0 }} exit={{ opacity: 0, x: 24 }}><header><h2>Уведомления</h2><button type="button" onClick={() => setState({ ...state, notifications: [] })}>Очистить</button></header>{state.notifications.map((item) => <article key={item.id}><Bell /><span><strong>{item.title}</strong><p>{item.text}</p></span></article>)}{!state.notifications.length ? <div className="nova-empty"><Bell /><strong>Новых уведомлений нет</strong></div> : null}</motion.aside> : null}</AnimatePresence>
      <AnimatePresence>{search ? <motion.div className="nova-search-overlay" initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} onClick={() => setSearch(false)}><section onClick={(event) => event.stopPropagation()}><label><Search /><input autoFocus value={searchQuery} onChange={(event) => setSearchQuery(event.target.value)} onKeyDown={(event) => { if (event.key === 'Escape') setSearch(false); }} placeholder="Приложения, файлы, заметки и настройки" /><kbd>ESC</kbd></label><div>{searchQuery ? results.map((result) => <button type="button" onClick={() => openApp(result.appId)} key={result.id}><AppIcon id={result.appId} label={false} /><span><strong>{result.title}</strong><small>{result.type}</small></span><Command /></button>) : appCatalog.slice(0, 6).map((app) => <button type="button" onClick={() => openApp(app.id)} key={app.id}><AppIcon id={app.id} label={false} /><span><strong>{app.label}</strong><small>Приложение</small></span></button>)}</div></section></motion.div> : null}</AnimatePresence>
      <AnimatePresence>{overview ? <motion.div className="nova-overview" initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }}><header><h2>Обзор</h2><div>{([1, 2, 3] as const).map((space) => <button className={state.activeSpace === space ? 'is-active' : ''} type="button" onClick={() => { setState({ ...state, activeSpace: space }); setOverview(false); }} key={space}>Рабочий стол {space}</button>)}</div><button type="button" onClick={() => setOverview(false)}><X /></button></header><section>{state.windows.map((window) => <button type="button" onClick={() => { setState(focusModernWindow({ ...state, activeSpace: window.space }, window.id)); setOverview(false); }} key={window.id}><AppIcon id={window.appId} label={false} /><strong>{window.title}</strong><small>Рабочий стол {window.space}</small></button>)}</section>{!state.windows.length ? <div className="nova-empty"><AppWindow /><strong>Нет открытых окон</strong></div> : null}</motion.div> : null}</AnimatePresence>
      <div className="nova-brightness-overlay" aria-hidden="true" />
    </div>
  </LabShell>;
}
